spring:
  profiles:
    active: dev, eureka_server, activemq
  application:
    name: users-gym-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER

  cloud:
    config:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  show-actuator: true

microservice:
  connection: activemq