server:
  port: 8080

# File path for storage initialization
initializationStorageFile:
  path: src/main/resources/static/InitialGymData.xlsx

logging:
  pattern:
    dateformat: hh:mm

# Mysql conexión
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gym_epam?zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    livereload:
      enabled: true
  profiles:
    active: jpa

validate.password: bcrypt
