spring:
  profiles:
    active: jpa
#    active: inmemory, elastic
  application:
    name: gym-final-project
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

validate.password: bcrypt

server:
  port: 8080

# File path for storage initialization
initializationStorageFile:
  path: src/main/resources/static/InitialGymData.xlsx

