server:
  port: 8082
#
#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#
#  cloud:
#    compatibility-verifier:
#      enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost

#application:
#  config:
#    training-url: http://localhost:8222/api/v1/training

resilience4j.circuitbreaker:
  instances:
    trainingCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    allCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10