spring:
  profiles:
    active: jpa
#      active: inmemory
  application:
    name: gym-final-project
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER
validate:
  password: bcrypt
  encoded:
    enabled: false

server:
  port: 8080

# File path for storage initialization
initializationStorageFile:
  path: src/main/resources/static/InitialGymData.xlsx
  active: false

