spring:
  profiles:
    active: dev
  application:
    name: gym-final-project
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER
#  config:
#    activate:
#      on-profile: dev

management:
  server:
    port: 9002
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
#      base-path: "/manage"

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true