server:
  port: 8080
app:
  repository: jpa
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_NAME:db_gym_main_service}
    username: ${MYSQL_USER:prod}
    password: ${MYSQL_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

# File path for storage initialization
initializationStorageFile:
  path: src/main/resources/static/InitialGymData.xlsx
  active: ${INITIALIZE_STORAGE:false}

validate:
  password: bcrypt
  encoded:
    enabled: true