server:
  port: 8080

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
feign:
  client:
    enabled: false

microservice:
#  integration: ${INTEGRATION:enabled}
  connection: ${CONNECTION:aws}