spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

    pool:
      block-if-full: true
      block-if-full-timeout: -1

      enabled: false
      idle-timeout: 30000
      max-connections: 1

      time-between-expiration-check: -1
      use-anonymous-producers: true
      # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000

