global:
  scrape_interval: 5s #scrape every 5 seconds
  evaluation_interval: 5s #evaluate rules every 5 secs

rule_files:
#  - "one_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.10.1:9090']
  - job_name: 'gym-final-project-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.1:9002'] #host and port
